services:
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
