services:
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
networks:
  default:
    external:
      name: academy-network
